//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBike.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marka
    {
        public Marka()
        {
            this.Bike = new HashSet<Bike>();
        }
    
        public int Id { get; set; }
        public string Ad { get; set; }
    
        public virtual ICollection<Bike> Bike { get; set; }
    }
}
